import { StoreProduct } from './types';

export const MOCK_STORE_PRODUCTS: StoreProduct[] = [
  // --- Category: Oils & Lubricants (زيوت ومحروقات) - 10 Products ---
  {
    id: 'PRD-MTL710',
    name: 'Motul 7100 10W40 4T 1L',
    nameAr: 'زيت موتول 7100 10W40 تخليقي 1 لتر',
    category: 'Oils',
    brand: 'Motul',
    price: 850,
    originalPrice: 950,
    isOffer: true,
    offerLabel: 'SALE',
    offerLabelAr: 'عرض خاص',
    image: 'https://images.unsplash.com/photo-1620059344427-4a008c3e8cb9?w=400&q=80',
    description: '100% Synthetic 4-Stroke motorcycle engine lubricant. Esters technology. High shear stability.',
    descriptionAr: 'زيت محركات رباعي الأشواط تخليقي بالكامل 100%. تكنولوجيا الإستر المتقدمة لحماية قصوى للمحرك وتروس السرعة.',
    stockCount: 45,
    soldCount: 120,
    isHidden: false,
    galleryUrls: [],
    specs: 'Viscosity: 10W40 | Volume: 1L | Type: Full Synthetic',
    specsAr: 'اللزوجة: 10W40 | الحجم: 1 لتر | النوع: تخليقي بالكامل'
  },
  {
    id: 'PRD-MTL300',
    name: 'Motul 300V 15W50 Double Ester Road Racing 1L',
    nameAr: 'زيت موتول 300V تخليقي مزدوج الإستر 1 لتر',
    category: 'Oils',
    brand: 'Motul',
    price: 1250,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1620059344427-4a008c3e8cb9?w=400&q=80',
    description: 'Factory Line Racing engine lubricant. Double Ester technology for maximum power output and reliability.',
    descriptionAr: 'زيت محركات السباق الرياضي المعتمد في الموتو جي بي. تقنية الإستر المزدوج لتحقيق أقصى عزم وقوة للمحرك في الظروف القاسية.',
    stockCount: 20,
    soldCount: 85,
    isHidden: false,
    galleryUrls: [],
    specs: 'Viscosity: 15W50 | Volume: 1L | Type: Factory Line',
    specsAr: 'اللزوجة: 15W50 | الحجم: 1 لتر | النوع: فكتوري لاين سباقات'
  },
  {
    id: 'PRD-YML104',
    name: 'Yamalube 10W40 Performance 4T 1L',
    nameAr: 'زيت يامالوب 10W40 أداء عالي 1 لتر',
    category: 'Oils',
    brand: 'Yamaha',
    price: 620,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1620059344427-4a008c3e8cb9?w=400&q=80',
    description: 'High performance mineral formulation specifically blended for Yamaha motorcycles.',
    descriptionAr: 'زيت محرك فائق الأداء مصمم خصيصاً وبشكل مثالي لمحركات ودراجات ياماها الرياضية والكروزر.',
    stockCount: 30,
    soldCount: 40,
    isHidden: false,
    galleryUrls: [],
    specs: 'Viscosity: 10W40 | Volume: 1L | Type: Mineral High Performance',
    specsAr: 'اللزوجة: 10W40 | الحجم: 1 لتر | النوع: معدني فائق الأداء'
  },
  {
    id: 'PRD-LQM4T1',
    name: 'Liqui Moly Street 4T 10W50 1L',
    nameAr: 'زيت ليكوي مولي الألماني 10W50 للطرقات 1 لتر',
    category: 'Oils',
    brand: 'Liqui Moly',
    price: 780,
    originalPrice: 850,
    isOffer: true,
    offerLabel: 'OFFER',
    offerLabelAr: 'خصم',
    image: 'https://images.unsplash.com/photo-1620059344427-4a008c3e8cb9?w=400&q=80',
    description: 'German premium high-performance motor oil. Ensures maximum performance and protection of the engine under all operating conditions.',
    descriptionAr: 'زيت محركات الألماني الممتاز عالي الأداء. يضمن حماية المحرك من الاحتكاك المباشر في درجات الحرارة العالية.',
    stockCount: 50,
    soldCount: 160,
    isHidden: false,
    galleryUrls: [],
    specs: 'Viscosity: 10W50 | OEM: German Standard | Type: Fully Synthetic',
    specsAr: 'اللزوجة: 10W50 | المنشأ: ألمانيا | النوع: تخليقي بالكامل'
  },
  {
    id: 'PRD-RPS4T4',
    name: 'Repsol Moto Sintetico 4T 10W40 1L',
    nameAr: 'زيت ريبسول 4T سينتيتيكو 10W40 لتر',
    category: 'Oils',
    brand: 'Repsol',
    price: 650,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1620059344427-4a008c3e8cb9?w=400&q=80',
    description: 'Synthetic oil providing exceptional startup protection and total engine hygiene.',
    descriptionAr: 'زيت تخليقي متطور يوفر حماية استثنائية عند التشغيل البارد ويحافظ على سلامة ونظافة الأجزاء الداخلية للمحرك.',
    stockCount: 25,
    soldCount: 38,
    isHidden: false,
    galleryUrls: [],
    specs: 'Viscosity: 10W40 | Volume: 1L | Type: Synthetic',
    specsAr: 'اللزوجة: 10W40 | الحجم: 1 لتر | النوع: تخليقي'
  },
  {
    id: 'PRD-MTLCHL',
    name: 'Motul Chain Lube Road C2 400ml',
    nameAr: 'اسبراي مشحم جنزير موتول C2 حجم 400 مل',
    category: 'Oils',
    brand: 'Motul',
    price: 450,
    originalPrice: 500,
    isOffer: true,
    offerLabel: '10% OFF',
    offerLabelAr: 'خصم 10%',
    image: 'https://images.unsplash.com/photo-1599839619722-39751411ea63?w=400&q=80',
    description: 'Colorless and sticky lubricant designed specifically for street motorcycle chains to decrease friction and wear.',
    descriptionAr: 'اسبراي عديم اللون عالي الالتصاق مصمم خصيصاً لتزييت جنازير الدراجات النارية وتقليل التآكل والحرارة.',
    stockCount: 60,
    soldCount: 310,
    isHidden: false,
    galleryUrls: [],
    specs: 'Volume: 400ml | Type: C2 Road Sticky | Nozzle included',
    specsAr: 'الحجم: 400 مل | النوع: مشحم جنزير لاصق C2 | مزود بأنبوب بخ'
  },
  {
    id: 'PRD-IPNBLU',
    name: 'IPONE Chain Spray Care Blue 250ml',
    nameAr: 'جيل جنزير ازرق ايبون الفرنسي 250 مل',
    category: 'Oils',
    brand: 'IPONE',
    price: 390,
    originalPrice: 480,
    isOffer: true,
    offerLabel: 'HOT',
    offerLabelAr: 'ساخن',
    image: 'https://images.unsplash.com/photo-1599839619722-39751411ea63?w=400&q=80',
    description: 'French premium blue chain grease. Perfect visibility of application, weather and water resistant.',
    descriptionAr: 'جيل تزييت أزرق فرنسي مميز. يعطي طبقة واقية مقاومة للماء والصدأ ولون رائع للجنزير يحسن المظهر العام.',
    stockCount: 15,
    soldCount: 95,
    isHidden: false,
    galleryUrls: [],
    specs: 'Volume: 250ml | Color: Electric Blue | Waterproof',
    specsAr: 'الحجم: 250 مل | اللون: أزرق كهربائي | مقاوم تماماً للغسيل والماء'
  },
  {
    id: 'PRD-LQMEFL',
    name: 'Liqui Moly Moto Engine Flush 250ml',
    nameAr: 'منظف دورة المحرك ليكوي مولي الألماني',
    category: 'Oils',
    brand: 'Liqui Moly',
    price: 320,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1616422934098-96425a176848?w=400&q=80',
    description: 'Cleans the engine internally before oil change. Removes black sludge, deposits and carbon.',
    descriptionAr: 'فلاش داخلي لتنظيف المحرك وإزالة الرواسب الكربونية والاتساخات قبل تصفية الزيت القديم لضمان أداء فعال للزيت الجديد.',
    stockCount: 35,
    soldCount: 64,
    isHidden: false,
    galleryUrls: [],
    specs: 'Volume: 250ml | Run time: 10 mins idle | Engine Safety: Safe',
    specsAr: 'الحجم: 250 مل | مدة التشغيل: 10 دقائق سلانسيه | الأمان: آمن بالكامل'
  },
  {
    id: 'PRD-CSTPW1',
    name: 'Castrol Power1 10W40 4T 1L',
    nameAr: 'زيت كاسترول باور 1 10W40 لتر',
    category: 'Oils',
    brand: 'Castrol',
    price: 520,
    originalPrice: 580,
    isOffer: true,
    offerLabel: 'SALE',
    offerLabelAr: 'تنزيل',
    image: 'https://images.unsplash.com/photo-1620059344427-4a008c3e8cb9?w=400&q=80',
    description: 'High performance engine oil with Power Release Formula for superior acceleration.',
    descriptionAr: 'زيت محرك متطور عالي الأداء بتركيبة إطلاق الطاقة التي تقلل الاحتكاك وتمنحك تسارعاً ممتازاً واستجابة فورية للمحرك.',
    stockCount: 40,
    soldCount: 145,
    isHidden: false,
    galleryUrls: [],
    specs: 'Viscosity: 10W40 | Volume: 1L | Type: Semi-Synthetic Power Release',
    specsAr: 'اللزوجة: 10W40 | الحجم: 1 لتر | النوع: نصف تخليقي بور ريليس'
  },
  {
    id: 'PRD-SHLADV',
    name: 'Shell Advance Ultra 10W40 1L',
    nameAr: 'زيت شيل إدوفانس ألترا تخليقي بالكامل',
    category: 'Oils',
    brand: 'Shell',
    price: 760,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1620059344427-4a008c3e8cb9?w=400&q=80',
    description: '100% synthetic motorcycle engine oil made from natural gas with Shell PurePlus Technology.',
    descriptionAr: 'زيت محركات تخليقي بالكامل 100% مصنع من الغاز الطبيعي بتكنولوجيا PurePlus الحاصلة على براءة اختراع لأقصى درجات حماية المحرك.',
    stockCount: 38,
    soldCount: 112,
    isHidden: false,
    galleryUrls: [],
    specs: 'Viscosity: 10W40 | Volume: 1L | Technology: Shell PurePlus',
    specsAr: 'اللزوجة: 10W40 | الحجم: 1 لتر | التكنولوجيا: شيل بيور بلس'
  },

  // --- Category: Safety Equipment (معدات أمان) - 10 Products ---
  {
    id: 'PRD-AGVK1S',
    name: 'AGV K1 S Full Face Sport Helmet',
    nameAr: 'خوذة أي جي في K1 S الرياضية الأصلية',
    category: 'Safety',
    brand: 'AGV',
    price: 11500,
    originalPrice: 13000,
    isOffer: true,
    offerLabel: 'SALE',
    offerLabelAr: 'عرض خاص',
    image: 'https://images.unsplash.com/photo-1558981852-426c6c22a060?w=400&q=80',
    description: 'The racing helmet for everyday road challenges. Aerodynamic shape, front air vents and customized spoiler.',
    descriptionAr: 'خوذة السباقات الرياضية المعتمدة للاستخدام اليومي من العلامة الإيطالية AGV. تصميم انسيابي مميز بمنافة تهوية محسنة وسبويلر خلفي.',
    stockCount: 8,
    soldCount: 22,
    isHidden: false,
    galleryUrls: [],
    specs: 'Safety: ECE 22.06 certified | Weight: 1500g | Retention: Double D-ring',
    specsAr: 'معيار الأمان: معتمد ECE 22.06 | الوزن: 1500 جرام | قفل الإغلاق: حلقة Double D'
  },
  {
    id: 'PRD-SHIE15',
    name: 'Shoei X-Fifteen Racing Pro Helmet',
    nameAr: 'خوذة شوي X-Fifteen الاحترافية الفاخرة',
    category: 'Safety',
    brand: 'Shoei',
    price: 26000,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1558981852-426c6c22a060?w=400&q=80',
    description: 'Premium absolute racing performance helmet. Ultimate aerodynamic profiling and FIM homologation.',
    descriptionAr: 'الخيار الأول لأبطال الموتو جي بي. خوذة الشوي اليابانية بتصميم هوائي متطور للمقاومة القصوى وسحب الرياح وثبات عالي السرعة.',
    stockCount: 4,
    soldCount: 10,
    isHidden: false,
    galleryUrls: [],
    specs: 'Material: AIM+ Multi-Fiber | Certification: FIM Racing | Country: Japan',
    specsAr: 'الخامة: AIM+ ألياف مركبة متعددة | الاعتماد: FIM للسباقات | بلد المنشأ: اليابان'
  },
  {
    id: 'PRD-ALPGLV',
    name: 'Alpinestars GP Pro V2 Leather Riding Gloves',
    nameAr: 'قفازات البين ستارز GP Pro V2 جلد سباقات الكاربون',
    category: 'Safety',
    brand: 'Alpinestars',
    price: 4800,
    originalPrice: 5300,
    isOffer: true,
    offerLabel: 'PROMO',
    offerLabelAr: 'خصم',
    image: 'https://plus.unsplash.com/premium_photo-1661962386869-90d0b005fe43?w=400&q=80',
    description: 'Premium full leather gloves with carbon fiber knuckle protectors. Developed on motoGP tracks.',
    descriptionAr: 'قفازات جلدية طويلة فاخرة مع حماية من ألياف الكربون لمفاصل اليد وجسر الاصبع الثالث والرابع لمنع الالتواء.',
    stockCount: 12,
    soldCount: 42,
    isHidden: false,
    galleryUrls: [],
    specs: 'Material: Goat & Kangaroo Leather | Protection: Carbon knuckle | Interface: Touchscreen',
    specsAr: 'الخامة: جلد ماعز وكانغارو فاخر | الحماية: مفاصل كاربون فايبر | شاشة اللمس: مدعومة'
  },
  {
    id: 'PRD-DNSR4J',
    name: 'Dainese Racing 4 Leather Jacket - Black/Gold',
    nameAr: 'جاكيت دانيز ريسينج 4 جلدي فاخر - أسود وذهبي',
    category: 'Safety',
    brand: 'Dainese',
    price: 18500,
    originalPrice: 21000,
    isOffer: true,
    offerLabel: 'EXCLUSIVE',
    offerLabelAr: 'حصري',
    image: 'https://plus.unsplash.com/premium_photo-1673356302067-aac3b545a362?w=400&q=80',
    description: 'An icon of sport leather collection. Premium Tutu cowhide leather with S1 elasticated fabric inserts and aluminum shoulder sliders.',
    descriptionAr: 'أيقونة جواكيت الجلد الرياضية من دانيز الإيطالية. مصنع من جلد البقر الفاخر المقاوم للاحتكاك مزود بصفائح ألومنيوم رياضية ممتازة على الأكتاف.',
    stockCount: 5,
    soldCount: 18,
    isHidden: false,
    galleryUrls: [],
    specs: 'Leather Type: Tutu Cowhide | Sliders: Interchangeable Aluminum | Thermal: Removable Liner',
    specsAr: 'نوع الجلد: توتو بقر سميك | سلايدرات الكتف: ألومنيوم قابل للتغيير | البطانة: شبكة مرنة'
  },
  {
    id: 'PRD-ALPSMX',
    name: 'Alpinestars SMX-6 V2 Performance Sport Boots',
    nameAr: 'حذاء البين ستارز SMX-6 V2 الرياضي للحماية',
    category: 'Safety',
    brand: 'Alpinestars',
    price: 9200,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1558981852-426c6c22a060?w=400&q=80',
    description: 'Advanced design microfibre sport riding boot. Offers supreme flexibility, protection, and comfort.',
    descriptionAr: 'رويال بوت رياضي للمحترفين مصمم من المايكروفايبر عالي التحمل ومزود بدعامة كاحل ميكانيكية متطورة لمنع الكسر والالتواء.',
    stockCount: 10,
    soldCount: 26,
    isHidden: false,
    galleryUrls: [],
    specs: 'Material: High tech microfiber | Protection: TPU heel & shin guards | Slider: Plastic toe slider',
    specsAr: 'الخامة: مايكروفايبر معالج | الحماية: دروع كعب وقصبة الساق TPU | السلايدر: أمامي قابل للاستبدال'
  },
  {
    id: 'PRD-LEAKNE',
    name: 'Leatt Dual Axis Knee and Shin Guards',
    nameAr: 'واقي ركبة وساق ليت ثنائي المحاور احترافي',
    category: 'Safety',
    brand: 'Leatt',
    price: 3400,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://plus.unsplash.com/premium_photo-1661962386869-90d0b005fe43?w=400&q=80',
    description: 'Anatomically correct pivoting design. CE certified for premium knee impact safety.',
    descriptionAr: 'واقي ركبة وساق احترافي مصمم بمحورين دوران ليحاكي الحركة الطبيعية للمفصل مع تقديم أعلى درجات الحماية والامتصاص للصدمات ECE.',
    stockCount: 15,
    soldCount: 47,
    isHidden: false,
    galleryUrls: [],
    specs: 'Pivots: Dual pivoting axle | Certification: EN1621-1 level 1 | Design: Lightweight',
    specsAr: 'المحور: دوران ثنائي طبيعي | الاعتماد: EN1621-1 تصنيف 1 | التصميم: خفيف ومريح للغاية'
  },
  {
    id: 'PRD-DNSWAV',
    name: 'Dainese Wave D1 G2 Back Protector Insert',
    nameAr: 'واقي ظهر دانيز ويف D1 G2 الممتص للدروع',
    category: 'Safety',
    brand: 'Dainese',
    price: 2800,
    originalPrice: 3200,
    isOffer: true,
    offerLabel: 'SALE',
    offerLabelAr: 'عرض',
    image: 'https://images.unsplash.com/photo-1558981852-426c6c22a060?w=400&q=80',
    description: 'Insertable spine armor for motorcycle jackets. Honeycomb core for lightweight elite energy dissipation.',
    descriptionAr: 'درع ظهر يوضع داخل الجاكيت لحماية العمود الفقري عند السقوط. تصميم قرص العسل الهيكلي لامتصاص وتشتيت كامل طاقة الضربة.',
    stockCount: 14,
    soldCount: 39,
    isHidden: false,
    galleryUrls: [],
    specs: 'Safety Level: Category II EN 1621.2 | Core: Aluminium honeycomb | Fit: Insert pocket',
    specsAr: 'مستوى الأمان: الفئة الثانية EN 1621.2 | النواة: خلية ألومنيوم | التركيب: جيب مدرج بالجاكيت'
  },
  {
    id: 'PRD-ALPBIO',
    name: 'Alpinestars Bionic Action Full Protection Jacket',
    nameAr: 'سبيكة حماية البين ستارز بيونيك اكشن كاملة',
    category: 'Safety',
    brand: 'Alpinestars',
    price: 6500,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://plus.unsplash.com/premium_photo-1673356302067-aac3b545a362?w=400&q=80',
    description: 'All-new, lightweight protective armor. Features CE certified grids for chest, back, shoulders and elbows.',
    descriptionAr: 'جاكيت درع خفيف وعملي يضم دروع حماية الظهر والصدر والأكتاف والكوع في قطعة واحدة متناسقة بتهوية ممتازة للطرق الممهدة والوعرة.',
    stockCount: 6,
    soldCount: 15,
    isHidden: false,
    galleryUrls: [],
    specs: 'Grids: Cell Technology | Back: EN 1621-2 | Chest: EN 1621-3',
    specsAr: 'التكنولوجيا: تكنولوجيا الخلايا | حماية الظهر: EN 1621-2 | حماية الصدر: EN 1621-3'
  },
  {
    id: 'PRD-HJCR11',
    name: 'HJC RPHA 11 Pro Carbon Helmet',
    nameAr: 'خوذة إتش جيه سي RPHA 11 برو كاربون',
    category: 'Safety',
    brand: 'HJC',
    price: 16500,
    originalPrice: 18000,
    isOffer: true,
    offerLabel: 'SALE',
    offerLabelAr: 'خصم',
    image: 'https://images.unsplash.com/photo-1558981852-426c6c22a060?w=400&q=80',
    description: 'Premium carbon fiber outer shell helmet. Lightweight, extreme ventilation and aerodynamic optimization.',
    descriptionAr: 'خوذة رياضية مصنوعة من ألياف الكربون بالكامل لهيكل فائق الخفة والصلابة. تهوية علوية وتصميم هيدروليكي ممتاز للسرعات العالية.',
    stockCount: 5,
    soldCount: 14,
    isHidden: false,
    galleryUrls: [],
    specs: 'Material: Pure Carbon Fiber | Weight: 1300g | Certification: DOT & ECE',
    specsAr: 'الخامة: ألياف كربون صافي | الوزن: 1300 جرام | الاعتماد: DOT و ECE الدولية'
  },
  {
    id: 'PRD-BELQLF',
    name: 'Bell Qualifier DLX MIPS Helmet - Matte Black',
    nameAr: 'خوذة بيل كواليفاير DLX MIPS سوداء مطفأة',
    category: 'Safety',
    brand: 'Bell',
    price: 7800,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1558981852-426c6c22a060?w=400&q=80',
    description: 'Full face helmet packed with features including MIPS multidirectional impact protection.',
    descriptionAr: 'خوذة رأس كاملة ممتازة مزودة بنظام MIPS لحماية الدماغ من قوى الدوران الناتجة عن الصدمات الزاوية وجيب مخصص لسماعات الانتركوم.',
    stockCount: 11,
    soldCount: 36,
    isHidden: false,
    galleryUrls: [],
    specs: 'Protection: MIPS Technology | Visor: Transitions Photochromic | Shell: Polycarbonate',
    specsAr: 'الحماية: تكنولوجيا MIPS | الفايزر: فوتوكروميك ذكي متحول تلقائياً | الهيكل: بولي كربونات'
  },

  // --- Category: Smart Accessories (اكسسوارات ذكية) - 10 Products ---
  {
    id: 'PRD-CRDPTK',
    name: 'Cardo Packtalk Edge Duo Set',
    nameAr: 'انتركوم كاردو باك توك ايدج ثنائي أصلي (قطعتين)',
    category: 'Smart',
    brand: 'Cardo',
    price: 18900,
    originalPrice: 19900,
    isOffer: true,
    offerLabel: 'DUO-SET',
    offerLabelAr: 'طقم مزدوج',
    image: 'https://images.unsplash.com/photo-1631557008707-425fdb946eaf?w=400&q=80',
    description: 'The world\'s best intercom system. JBL Sound, Dynamic Mesh Communication 2.0, waterproof and magnetic Air Mount.',
    descriptionAr: 'أقوى نظام تواصل وانتركوم للدراجات النارية في العالم. صوت نقي بفضل سماعات JBL الأمريكية، مقاوم للماء، وقفل مغناطيسي ومسافة 1.6 كم.',
    stockCount: 5,
    soldCount: 55,
    isHidden: false,
    galleryUrls: [],
    specs: 'Sound: JBL speakers 40mm | Comm: DMC mesh 2nd Gen | Voice: Natural voice engine',
    specsAr: 'الصوت: مكبرات JBL مقاس 40 مل | ميزة الاتصال: شبكة DMC الجيل الثاني | التحكم: أوامر صوتية'
  },
  {
    id: 'PRD-SEN50S',
    name: 'Sena 50S Mesh Radio Single headset',
    nameAr: 'سماعة انتركوم سينّا 50S الفردية',
    category: 'Smart',
    brand: 'Sena',
    price: 13500,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&q=80',
    description: 'Harman Kardon premium audio experience. Mesh Intercom, Bluetooth 5.0, digital assistant companion access.',
    descriptionAr: 'تجربة سماعات هارمان كاردون الصوتية الاستثنائية. تدعم الاتصال بخطوط مش متعددة واتصال البلوتوث والوصول للمساعد الصوتي الذكي.',
    stockCount: 8,
    soldCount: 30,
    isHidden: false,
    galleryUrls: [],
    specs: 'Audio: Harman Kardon speakers | Bluetooth: 5.0 | Range: up to 8 km mesh',
    specsAr: 'الصوت: سبيكرات Harman Kardon | بلوتوث: 5.0 | المدى: حتى 8 كم بالشبكة'
  },
  {
    id: 'PRD-SPCPRO',
    name: 'SP Connect Moto Mount Pro Metallic',
    nameAr: 'حامل جوال إس بي كونكت برو للدراجات',
    category: 'Smart',
    brand: 'SP Connect',
    price: 2200,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1631557008707-425fdb946eaf?w=400&q=80',
    description: 'CNC machined aircraft grade aluminum phone bracket. Dynamic anti-vibration damping core integration.',
    descriptionAr: 'حامل موبايل من الألومنيوم المقاوم للصدأ ومصنوع بآلات CNC الدقيقة، يثبت بقوة وخفة على مقود الدراجة ويحمي الهاتف من السقوط.',
    stockCount: 15,
    soldCount: 140,
    isHidden: false,
    galleryUrls: [],
    specs: 'Material: Aircraft Alum | Orientation: Portrait / Landscape | Install: Handlebar',
    specsAr: 'الخامة: ألومنيوم طائرات متين | الوضعية: أفقي أو رأسي 360 | التركيب: على المقود الكليبون'
  },
  {
    id: 'PRD-QLKDVP',
    name: 'Quad Lock Motorcycle Vibration Dampener',
    nameAr: 'امتصاص اهتزاز كاميرا الهاتف كواد لوك',
    category: 'Smart',
    brand: 'Quad Lock',
    price: 950,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1631557008707-425fdb946eaf?w=400&q=80',
    description: 'Protects your smartphone camera image stabilizer. Reduces up to 90% in high-frequency vibrations.',
    descriptionAr: 'حامي وممتص صدمات واهتزازات الهاتف المتميز من كواد لوك لمنع تلف مثبت الكاميرا العشاري بالهواتف الذكية نتيجة ترددات المحرك.',
    stockCount: 40,
    soldCount: 220,
    isHidden: false,
    galleryUrls: [],
    specs: 'Damping: Silicon suspension | Fit: All Quad Lock mounts | Installation: Tool included',
    specsAr: 'امتصاص: معلق سيليكون مرن | التوافق: جميع حوامل كواد لوك | التركيب: مرفق مفتاح الربط'
  },
  {
    id: 'PRD-GPRH12',
    name: 'GoPro Hero 12 Black action camera',
    nameAr: 'كاميرا جوبرو هيرو 12 سوداء للتصوير',
    category: 'Smart',
    brand: 'GoPro',
    price: 24500,
    originalPrice: 27000,
    isOffer: true,
    offerLabel: 'HOT DEAL',
    offerLabelAr: 'صفقة حارة',
    image: 'https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?w=400&q=80',
    description: 'The ultimate action camera for motovlogging. Hypersmooth 6.0 stabilization, HDR 5.3K video, wireless audio.',
    descriptionAr: 'كاميرا الأكشن الأقوى لتسجيل رحلاتك ومقاطع الموتوفلوج. ثبات فائق هابرسيركل 6.0، دقة وضوح 5.3K، وتسجيل صوتي نقي لاسلكي.',
    stockCount: 3,
    soldCount: 16,
    isHidden: false,
    galleryUrls: [],
    specs: 'Video Resolution: 5.3K60 / 4K120 | Stabilization: HyperSmooth 6.0 | Waterproof: 10m',
    specsAr: 'دقة الفيديو: 5.3K60 / 4K120 | التثبيت البصري: HyperSmooth 6.0 | مقاومة الماء: 10 أمتار'
  },
  {
    id: 'PRD-INVK3D',
    name: 'Innovv K3 Dual Camera Motocycled System',
    nameAr: 'نظام كاميرات دراجات مزدوجة Innovv K3 ذكي',
    category: 'Smart',
    brand: 'Innovv',
    price: 12800,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?w=400&q=80',
    description: 'Dual channel full HD 1080P recording. Features smart ignition trigger, GPS and WiFi connectivity app.',
    descriptionAr: 'كاميرتان أمامية وخلفية لتسجيل الرحلات بشكل آلي ومستمر وحماية الدراجة. دقة 1080P ومقاومة للماء بجي بي اس مدمج وتطبيق جوال.',
    stockCount: 4,
    soldCount: 9,
    isHidden: false,
    galleryUrls: [],
    specs: 'Cameras: 2x 1080P Sony Sensors | Connectivity: Wi-Fi & GPS | Protection: IP67',
    specsAr: 'الكاميرات: عدستان حساس سوني 1080 | الاتصالات: وايرلس وجي بي اس | الحماية: مقاوم للماء غبار IP67'
  },
  {
    id: 'PRD-XIAAIR',
    name: 'Xiaomi Portable Electric Compressor 2',
    nameAr: 'منفاخ إطارات شاومي الكهربائي المحمول 2',
    category: 'Smart',
    brand: 'Xiaomi',
    price: 1850,
    originalPrice: 2200,
    isOffer: true,
    offerLabel: 'BESTSELLER',
    offerLabelAr: 'الأكثر مبيعاً',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&q=80',
    description: 'Upgraded smart battery-powered tire pump. Auto stopping sensor, digital screen, multipurpose nozzle valve.',
    descriptionAr: 'الجيل الثاني من منفاخ الإطارات شاومي الذكي المحمول. شحن سريع للبطارية، شاشة ديجيتال، توقف تلقائي للنفخ وتوفير ضوء ليد مدمج.',
    stockCount: 25,
    soldCount: 185,
    isHidden: false,
    galleryUrls: [],
    specs: 'Pressure Range: 0.2 - 10.3 bar | Battery: USB Type-C | Screen: LCD Display',
    specsAr: 'مدى الضغط: 0.2 - 10.3 بار | البطارية: شحن تايب سي | الشاشة: ال سي دي رقمية'
  },
  {
    id: 'PRD-GPSTRK',
    name: 'GPS Smart Anti-Theft Tracker LTE-M',
    nameAr: 'جهاز تتبع بجي بي اس الذكي ومقاوم للسرقة للدرجات',
    category: 'Smart',
    brand: 'Trackerly',
    price: 3500,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1631557008707-425fdb946eaf?w=400&q=80',
    description: 'Instant motion alarm notifications on smartphone. Live tracking location with backup battery.',
    descriptionAr: 'جهاز أمان وتتبع مباشر وحي لمكان الدراجة على الخريطة، مزود بحساس اهتمام يرسل تنيهات مباشرة على الموبايل في وضع السكون والسرقة.',
    stockCount: 18,
    soldCount: 75,
    isHidden: false,
    galleryUrls: [],
    specs: 'Battery life: up to 15 days active | Network: Global LTE-M SIM | Size: Compact',
    specsAr: 'عمر البطارية: يصل لـ 15 يوماً | الشبكة: شريحة عالمية LTE-M | الحجم: صغير ومخفي تماماً'
  },
  {
    id: 'PRD-FRDCOM',
    name: 'FreedConn T-COM VB Bluetooth Intercom',
    nameAr: 'انتركوم فريدكون T-COM VB الاقتصادي',
    category: 'Smart',
    brand: 'FreedConn',
    price: 2400,
    originalPrice: 2800,
    isOffer: true,
    offerLabel: 'BUDGET',
    offerLabelAr: 'اقتصادي',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&q=80',
    description: 'Affordable high performance motorcycle riding intercom. Offers clear audio quality and stable Bluetooth link.',
    descriptionAr: 'انتركوم فريدكون الشهير بالأداء الاقتصادي العالي والقوي للمكالمات والاستماع للموسيقى وسهولة التوافق والاتصال مع الهواتف الذكية.',
    stockCount: 15,
    soldCount: 110,
    isHidden: false,
    galleryUrls: [],
    specs: 'Bluetooth: 4.1 | Connection distance: Up to 800m | Battery life: 10h talk',
    specsAr: 'بلوتوث: 4.1 | نطاق الاتصال: حتى 800 متر | عمر البطارية: 10 ساعات استخدام'
  },
  {
    id: 'PRD-SOMAN1',
    name: 'Soman Smart Helmet Bluetooth Headset',
    nameAr: 'سماعة خوذة بلوتوث ذكية SOMAN الرياضية',
    category: 'Smart',
    brand: 'Soman',
    price: 1800,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&q=80',
    description: 'Direct mounting high volume audio set. Excellent isolation and wind-noise cancelation technology.',
    descriptionAr: 'سماعة داخلية سهلة التثبيت داخل أي خوذة تمنح صوتاً ناصع النقاء ومستويات تضخيم ممتازة وعزل كامل للرياح والضوضاء الخارجية.',
    stockCount: 22,
    soldCount: 46,
    isHidden: false,
    galleryUrls: [],
    specs: 'Battery Capacity: 800mAh | Charge: Type-C | Audio: Dual stereo drivers',
    specsAr: 'سعة البطارية: 800 مللي أمبير | شحن: تايب سي | ملف الصوت: درايفر استريو ثنائي'
  },

  // --- Category: Spare Parts (قطع غيار) - 10 Products ---
  {
    id: 'PRD-BRMPAD',
    name: 'Brembo Red Sintered Front Brake Pads',
    nameAr: 'تيل فرامل بريمبو الإيطالي الأحمر أمامي نفاذ',
    category: 'Parts',
    brand: 'Brembo',
    price: 1450,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1533558701576-23c65e0272fb?w=400&q=80',
    description: 'Sintered alloy high performance sports bake pads. Ultimate braking performance and durable life cycle.',
    descriptionAr: 'تيل فرامل رياضي أصلي ومستورد من العلامة العريقة بريمبو الإيطالية. يعطي ثبات وقدرة كبح فائقة وعمر طويل الأمد.',
    stockCount: 22,
    soldCount: 94,
    isHidden: false,
    galleryUrls: [],
    specs: 'Material: Sintered Metal alloy | Position: Front | Safe in: Wet / Dry',
    specsAr: 'الخامة: معدن ملبد عالي الاحتكاك | الاتجاه: أمامي | الأمان: أداء ممتاز رطب وجاف'
  },
  {
    id: 'PRD-NGKIRD',
    name: 'NGK Iridium Spark Plug CR9EIX',
    nameAr: 'بوجيه ان جي كي ايريديوم رياضي فائق الأداء',
    category: 'Parts',
    brand: 'NGK',
    price: 450,
    originalPrice: 550,
    isOffer: true,
    offerLabel: 'POPULAR',
    offerLabelAr: 'رائج',
    image: 'https://images.unsplash.com/photo-1582218949811-002f2324dc25?w=400&q=80',
    description: 'Iridium alloy tip spark plug. Consistently stable ignition, improved acceleration responses and durable life.',
    descriptionAr: 'بوجيه إيريديوم ياباني يضمن حرق مثالي ومستقر تماماً للوقود، استجابة أسرع لدواسة البنزين وتوفير باستهلاك الوقود.',
    stockCount: 80,
    soldCount: 420,
    isHidden: false,
    galleryUrls: [],
    specs: 'Model: CR9EIX | Thread Size: 10mm | Reach: 19mm',
    specsAr: 'الموديل: CR9EIX | مقاس السن: 10 مل | عمق الوصول: 19 مل سن طويل'
  },
  {
    id: 'PRD-DIDCHN',
    name: 'DID 520 VX3 Pro Gold Chain 120 Links',
    nameAr: 'جنزير دي آي دي الياباني الذهبي الاحترافي',
    category: 'Parts',
    brand: 'DID',
    price: 3800,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1599839619722-39751411ea63?w=400&q=80',
    description: 'Japanese gold O-Ring reinforced chain. Maximum durability under heavy speed acceleration.',
    descriptionAr: 'الجنزير الذهبي الياباني المقوى بحلقات O-Ring لمنع تسرب الشحوم ومقاومة الاحتكاك في المسافات الطويلة والسرعات العالية.',
    stockCount: 12,
    soldCount: 63,
    isHidden: false,
    galleryUrls: [],
    specs: 'Pitch: 520 | Length: 120 Links | Connection: Rivet master link',
    specsAr: 'العرض: 520 | الطول: 120 حلقة | القفل: قفل مبرشم ذهبي'
  },
  {
    id: 'PRD-JTSPRK',
    name: 'JT Steel Rear Sprocket 45T',
    nameAr: 'ترس تروس خلفي ستيل جي تي 45 سن',
    category: 'Parts',
    brand: 'JT Sprockets',
    price: 1600,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1533558701576-23c65e0272fb?w=400&q=80',
    description: 'C49 high carbon steel rear sprocket. Strongest steel gear available, extremely durable and precise.',
    descriptionAr: 'ترس خلفي مصنوع بدقة متناهية من الفولاذ الكربوني المقاوم للحرارة والاحتكاك لزيادة قوة عزم الدوران وتحسين سحب الآلة.',
    stockCount: 16,
    soldCount: 40,
    isHidden: false,
    galleryUrls: [],
    specs: 'Teeth count: 45T | Pitch compatibility: 520 | Material: C49 Steel',
    specsAr: 'عدد الأسنان: 45 سن | العرض المتوافق: 520 | الخامة: فولاذ كربوني صلب C49'
  },
  {
    id: 'PRD-YASBAT',
    name: 'Yuasa YTX9-BS Maintenance-Free Battery',
    nameAr: 'بطارية يواسا اليابانية أصلية خالية من الصيانة',
    category: 'Parts',
    brand: 'Yuasa',
    price: 2400,
    originalPrice: 2600,
    isOffer: true,
    offerLabel: 'WARRANTY',
    offerLabelAr: 'مع ضمان',
    image: 'https://images.unsplash.com/photo-1582218949811-002f2324dc25?w=400&q=80',
    description: 'The industry gold standard motorcycle battery. Ultimate startup CCA power and acid pack included.',
    descriptionAr: 'معيار البطاريات الذهبي في العالم. تعطي أعلى تيار تشغيل وقدرة تدوير للمحرك، قابلة للشحن دون الحاجة لإعادة التزويد بالحمض.',
    stockCount: 9,
    soldCount: 88,
    isHidden: false,
    galleryUrls: [],
    specs: 'Model: YTX9-BS | Voltage: 12V | Capacity: 8Ah | CCA: 135A',
    specsAr: 'الموديل: YTX9-BS | الفولت: 12 فولت | السعة: 8 أمبير/س | تيار التدوير: 135 أمبير'
  },
  {
    id: 'PRD-KNFAIR',
    name: 'K&N Race Performance Air Filter',
    nameAr: 'فلتر هواء كي اند ان رياضي لزيادة تدفق الهواء',
    category: 'Parts',
    brand: 'K&N',
    price: 2900,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1582218949811-002f2324dc25?w=400&q=80',
    description: 'Washable and reusable lifetime filter. Boosts airflow by up to 50% for maximum engine performance.',
    descriptionAr: 'فلتر رياضي عالي الأداء من كي أند إن قابل للغسيل والترطيب وإعادة الاستخدام مدى الحياة. يزيد تدفق الهواء بنسبة 50%.',
    stockCount: 14,
    soldCount: 37,
    isHidden: false,
    galleryUrls: [],
    specs: 'Type: Multi-layer gauze | Washable: Yes, oilable | Expected life: Lifetime',
    specsAr: 'النوع: شاش مرشح متعدد الطبقات | قابل للغسل: نعم | العمر الافتراضي: دائم مدى الحياة'
  },
  {
    id: 'PRD-AKREXC',
    name: 'Akrapovic Slip-On Exhaust Carbon System',
    nameAr: 'شكمان دبه اكرابوفيك الاصلي ألياف الكربون',
    category: 'Parts',
    brand: 'Akrapovic',
    price: 23500,
    originalPrice: 26000,
    isOffer: true,
    offerLabel: 'EXCLUSIVE',
    offerLabelAr: 'حصري',
    image: 'https://images.unsplash.com/photo-1533558701576-23c65e0272fb?w=400&q=80',
    description: 'Elite racing look and signature deep exhaust sound. Real carbon fiber muffler sleeve and end cap.',
    descriptionAr: 'شكمان اكرابوفيك السلوفيني الحقيقي من الكاربون فايبر بالكامل لتقديم صوت رياضي عميق للماكينات، وتخفيف الوزن وزيادة عدد الأحصنة.',
    stockCount: 2,
    soldCount: 8,
    isHidden: false,
    galleryUrls: [],
    specs: 'Material: Carbon fiber & Titanium | Weight loss: -2.3 kg | Power gain: +1.8 HP',
    specsAr: 'المادة: ألياف كربون وتيتانيوم | تقليل الوزن: -2.3 كجم | زيادة طاقة المحرك: +1.8 حصان'
  },
  {
    id: 'PRD-MCHRD6',
    name: 'Michelin Road 6 Radial Front Riding Tire',
    nameAr: 'إطار كاوتش ميشلان رود 6 أمامي استيراد',
    category: 'Parts',
    brand: 'Michelin',
    price: 6800,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1533558701576-23c65e0272fb?w=400&q=80',
    description: 'Industry-leading wet grip and durable long distance radial compound.',
    descriptionAr: 'إطار ميشلان الأقوى والأطول عمراً في فئة الاستخدام اليومي والسفر والسياحة ثنائي المركبات 2CT لثبات خرافي في مياه المطر والميول الحادة.',
    stockCount: 8,
    soldCount: 44,
    isHidden: false,
    galleryUrls: [],
    specs: 'Size: 120/70 ZR17 | Load Index: 58W | Type: Radial Tubeless',
    specsAr: 'المقاس: 120/70 ZR17 | معامل الحمل: 58W | النوع: راديال بدون أنبوب داخلي تيوبلس'
  },
  {
    id: 'PRD-PRLROS',
    name: 'Pirelli Diablo Rosso IV Rear Sport Tire',
    nameAr: 'إطار ميشلان بيريللي ديابلو روسو 4 خلفي',
    category: 'Parts',
    brand: 'Pirelli',
    price: 9400,
    originalPrice: 10500,
    isOffer: true,
    offerLabel: 'CORSA',
    offerLabelAr: 'رياضي',
    image: 'https://images.unsplash.com/photo-1533558701576-23c65e0272fb?w=400&q=80',
    description: 'The latest generation of Pirelli sporting tire, providing riders with maximum dry and wet grip.',
    descriptionAr: 'إطار بيريللي الرياضي الفخم من الجيل الرابع، يمنح ركاب السوبر بايك عزم الإمساك التام بالأسفلت وثباتاً مطلقاً في المنعطفات.',
    stockCount: 6,
    soldCount: 29,
    isHidden: false,
    galleryUrls: [],
    specs: 'Size: 180/55 ZR17 | Compound: Dual Compound Silica | Origin: Germany',
    specsAr: 'المقاس: 180/55 ZR17 | التركيب: مركب السيليكا الثنائي | المنشأ: ألمانيا'
  },
  {
    id: 'PRD-EBCROT',
    name: 'EBC Brakes Floating Front Rotor Disk',
    nameAr: 'طنبورة ديسك فرامل أمامية عائمة EBC',
    category: 'Parts',
    brand: 'EBC Brakes',
    price: 4900,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1533558701576-23c65e0272fb?w=400&q=80',
    description: 'High friction floating rotor disk for immediate stopping leverage and cooling performance.',
    descriptionAr: 'ديسك فرامل عائم عالي الاحتكاك والتهوية من شركة EBC الإنجليزية يعزز قوة الكبح بشكل ملحوظ ويمنع التواء الطوابير بفعل الحرارة.',
    stockCount: 12,
    soldCount: 33,
    isHidden: false,
    galleryUrls: [],
    specs: 'Diameter: 310mm | Material: Heat-treated carbon steel | Hub: Alloy',
    specsAr: 'القطر: 310 مل | المادة: فولاذ معالج حرارياً | القاعدة: سبيكة رياضية خفيفة'
  },

  // --- Category: Lifestyle Products (منتجات لايف ستايل) - 10 Products ---
  {
    id: 'PRD-VR46BN',
    name: 'Valentino Rossi VR46 Classic Beanie',
    nameAr: 'ايس كاب فالنتينو روسي VR46 كلاسيك',
    category: 'Lifestyle',
    brand: 'VR46',
    price: 750,
    originalPrice: 850,
    isOffer: true,
    offerLabel: 'SALES',
    offerLabelAr: 'تنزيل',
    image: 'https://images.unsplash.com/photo-1582218949811-002f2324dc25?w=400&q=80',
    description: 'Doctor 46 design embroidered beanie, premium comfortable wool material.',
    descriptionAr: 'آيس كاب رسمي دكتور فالنتينو روسي الرقم 46 التاريخي من الصوف عالي الجودة والتدفئة للشتاء وأوقات الرحلات الباردة.',
    stockCount: 16,
    soldCount: 50,
    isHidden: false,
    galleryUrls: [],
    specs: 'Size: One size fits all | Theme: VR46 MotoGP | Material: 100% Acrylic',
    specsAr: 'المقاس: مقاس موحد للجميع | الهوية: فالنتينو روسي VR46 | المادة: 100% صوف أكريليك'
  },
  {
    id: 'PRD-ALPPACK',
    name: 'Alpinestars City Flight 25L Waterproof Backpack',
    nameAr: 'حقيبة ظهر البين ستارز الطائرة مقاومة للماء 25 لتر',
    category: 'Lifestyle',
    brand: 'Alpinestars',
    price: 2400,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&q=80',
    description: 'Dynamic aerodynamic design laptop backpack. Integrated helmet carrying pouch.',
    descriptionAr: 'حقيبة ظهر رياضية قشرة انسيابية تخفف سحب الرياح ومقاومة للمطر تماماً، تتسع للابتوب والأوراق ومزودة بحامل شبكي جانبي للخوذة.',
    stockCount: 8,
    soldCount: 33,
    isHidden: false,
    galleryUrls: [],
    specs: 'Capacity: 25L | Waterproof Rain Cover: Yes | Helmet holder: Built-in',
    specsAr: 'السعة: 25 لتر | غطاء المطر: مدمج ومقاوم | حامل خوذة: متوفر بشبكة خارجية'
  },
  {
    id: 'PRD-MNSMUG',
    name: 'Monster Energy Thermal Travel Mug Black 500ml',
    nameAr: 'كوب حافظ حرارة مونستر انيرجي ستيل لرحلات',
    category: 'Lifestyle',
    brand: 'Monster',
    price: 450,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1582218949811-002f2324dc25?w=400&q=80',
    description: 'Double walled stainless steel travel flask. Keeps hot for 12h and cold for 24h.',
    descriptionAr: 'ترمس ومحافظ سوائل من الفولاذ الثنائي المعزول بطبقة تفريغ. يحافظ على سخونة قهوتك وبرودة مشروباتك طوال الرحلة.',
    stockCount: 20,
    soldCount: 110,
    isHidden: false,
    galleryUrls: [],
    specs: 'Volume: 500ml | Stainless Steel Grade: 304 | Thermal loss: 12h Hot',
    specsAr: 'الحجم: 500 مل | درجة الستانلس ستيل: 304 صحي | الكفاءة: يحفظ السخونة 12 ساعة'
  },
  {
    id: 'PRD-DUCKCH',
    name: 'Ducati Corse Premium Leather Keychain',
    nameAr: 'ميدالية مفاتيح جلد دوكاتي كورس الرياضية أصلية',
    category: 'Lifestyle',
    brand: 'Ducati',
    price: 300,
    originalPrice: 400,
    isOffer: true,
    offerLabel: 'SALE',
    offerLabelAr: 'تنزيل',
    image: 'https://images.unsplash.com/photo-1582218949811-002f2324dc25?w=400&q=80',
    description: 'Genuine calf leather lanyard accessory with embossed metallic badge.',
    descriptionAr: 'ميدالية فاخرة لتعليق مفاتيح دراجتك النارية بتطريز وحفر فني جذاب لشعار دوكاتي كورس الرياضية من الجلد الطبيعي وحلقة معدنية قوية.',
    stockCount: 50,
    soldCount: 190,
    isHidden: false,
    galleryUrls: [],
    specs: 'Material: Genuine calf skin leather | Buckle: Quick release steel ring',
    specsAr: 'الخامة: جلد جاموسي طبيعي | الحلقة: معدن ستيل مقاوم للصدأ'
  },
  {
    id: 'PRD-KWSCAP',
    name: 'Kawasaki Racing Team Official Green Cap',
    nameAr: 'كاب فريق كواساكي سبورت الأخضر الأصلي',
    category: 'Lifestyle',
    brand: 'Kawasaki',
    price: 650,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1582218949811-002f2324dc25?w=400&q=80',
    description: 'Show your colors for Kawasaki KRT, high details embroidered classic team cap.',
    descriptionAr: 'عبّر عن شغفك بلون النينجا الشهير مع كاب فريق كواساكي الرياضي KRT بتطريز ثلاثي الأبعاد فائق ومميز وتعديل خلفي مريح لحجم الرأس.',
    stockCount: 15,
    soldCount: 45,
    isHidden: false,
    galleryUrls: [],
    specs: 'Material: 100% Cotton | Peak type: Curved | Adjustment: Strapback buckle',
    specsAr: 'الخامة: قطن 100% مريح | الحافة: دائرية كلاسيك | التعديل: إبزيم خلفي متين'
  },
  {
    id: 'PRD-YSMTSH',
    name: 'Yoshimura Performance Black Cotton T-Shirt',
    nameAr: 'تي شيرت يوشيمورا أسود قطن 100% لراكبي الدراجات',
    category: 'Lifestyle',
    brand: 'Yoshimura',
    price: 800,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&q=80',
    description: 'Limited edition Japan racing heritage heavy weight premium combed cotton.',
    descriptionAr: 'نسخة محدودة من تيشرتات يوشيمورا شكمانات اليابانية من القطن المغزول فائق الجودة والتهوية والمقاوم للتمدد والانكماش.',
    stockCount: 12,
    soldCount: 54,
    isHidden: false,
    galleryUrls: [],
    specs: 'Fabric: Combed heavy cotton | Stitching: Reinforced double-needle',
    specsAr: 'القماش: قطن ثقيل ممشط | الخياطة: مزدوجة لمقاومة الحركة والاستخدام'
  },
  {
    id: 'PRD-OKLBLC',
    name: 'Oakley Comfort Windproof Balaclava',
    nameAr: 'بالاكلافا وماسك وجه اوكلي الأصلي ضد الرياح والغبار',
    category: 'Lifestyle',
    brand: 'Oakley',
    price: 550,
    originalPrice: 650,
    isOffer: true,
    offerLabel: 'COMBO',
    offerLabelAr: 'تنزيل',
    image: 'https://images.unsplash.com/photo-1582218949811-002f2324dc25?w=400&q=80',
    description: 'Extremely thin, breathable and wind shielding fabric. Fits comfortably under all helmet sizes.',
    descriptionAr: 'قناع وجه ممتاز خفيف للغاية ويسمح بالتنفس بمرونة تامة بينما يمنع جفاف الوجه وتخلل هواء السفر والتراب داخل الخوذة.',
    stockCount: 30,
    soldCount: 180,
    isHidden: false,
    galleryUrls: [],
    specs: 'Material: Lycra dry mesh blend | Stitching: Flatlock seams | Wind protection: High',
    specsAr: 'الخامة: ليكرا بفتحات تبريد | الخياطة: خيوط مسطحة مانعة للحكة | صد الهواء: ممتاز'
  },
  {
    id: 'PRD-RDRBAG',
    name: 'Ride Rich Deluxe Padded Helmet Bag',
    nameAr: 'حقيبة خوذ ديلوكس مبطنة رايد ريتش الفاخرة لرحلات',
    category: 'Lifestyle',
    brand: 'Ride Rich',
    price: 1950,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1582218949811-002f2324dc25?w=400&q=80',
    description: 'Thick inner fleece protective casing to guard your helmet visor from scratches and impacts.',
    descriptionAr: 'حقيبة خوذة استثنائية مبطنة من الداخل بفرو الفليس الناعم جداً لمنع أي خدوش تذكر للفاير أو طلاء الخوذة الفخم أثناء الحفظ أو الطيران.',
    stockCount: 7,
    soldCount: 28,
    isHidden: false,
    galleryUrls: [],
    specs: 'Lining: Anti-scratch fleece | Shell: Rugged nylon cordura | Fits: ADV and race helmets',
    specsAr: 'البطانة: صوف فليس ضد الخدوش | الخارجية: نايلون كوردورا الخشن | القدرة: تتسع لجميع المقاسات'
  },
  {
    id: 'PRD-BMWWLT',
    name: 'BMW Motorrad Classic Leather Wallet',
    nameAr: 'محفظة جلدية كلاسيكية من بي إم دبليو موتوراد',
    category: 'Lifestyle',
    brand: 'BMW',
    price: 1400,
    originalPrice: 0,
    isOffer: false,
    offerLabel: '',
    offerLabelAr: '',
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&q=80',
    description: 'Elegant genuine leather wallet with a embossed BMW metal badge. Multiple card slots and cash divider.',
    descriptionAr: 'محفظة نقود وبطاقات فاخرة مصنوعة من الجلد الطبيعي وتحمل شعار بي إم دبليو موتوراد المعدني البارز مع فتحات متعددة للبطاقات الشخصية.',
    stockCount: 15,
    soldCount: 37,
    isHidden: false,
    galleryUrls: [],
    specs: 'Material: Genuine Leather | Certification: BMW Official | Dimensions: 11x9cm',
    specsAr: 'الخامة: جلد طبيعي فاخر | الترخيص: رسمي من بي إم دبليو | الأبعاد: 11 × 9 سم'
  },
  {
    id: 'PRD-YMHJKT',
    name: 'Yamaha Racing Team Softshell Riding Jacket',
    nameAr: 'جاكيت ياماها ريسينج الرياضي سوفتشيل',
    category: 'Lifestyle',
    brand: 'Yamaha',
    price: 2900,
    originalPrice: 3400,
    isOffer: true,
    offerLabel: 'WINTER',
    offerLabelAr: 'شتوي للرحلات',
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&q=80',
    description: 'Comfortable fleece lined softshell riding coat. Windproof and showerproof, perfect for touring.',
    descriptionAr: 'جاكيت سوفتشيل مقاوم للمياه ومقاوم لصد الرياح الشديدة من الداخل مبطن بالقطيفة والحرير لمنح الدفء التام والتهوية المثالية أثناء القيادة.',
    stockCount: 10,
    soldCount: 42,
    isHidden: false,
    galleryUrls: [],
    specs: 'Features: Fleece interior thermal | Pockets: 3 zippered | Protection: Mild abrasion resistant',
    specsAr: 'الخصائص: مبطن حراري صوف دافئ | الجيوب: 3 بسحاب حماية | الحماية: مقاوم بسيط للاحتكاك والخدوش'
  }
];
